# Source: https://distrobox.it/usage/distrobox-assemble/
[tumbleweed_dev]
replace=true
#image=registry.opensuse.org/opensuse/distrobox
image=registry.opensuse.org/opensuse/tumbleweed
#additional_packages="acpi bash-completion findutils iproute iputils sensors inotify-tools unzip"
#additional_packages="net-tools nmap openssl procps psmisc rsync man tig tmux tree vim nvim htop xclip yt-dlp"
#additional_packages="just"
additional_packages="nvim"
additional_packages="git git-credential-libsecret"
#additional_packages="patterns-devel-base-devel_basis"
#additional_packages="ShellCheck ansible-lint clang clang-tools codespell ctags desktop-file-utils gcc jq"
#additional_packages="kubernetes-client helm"
init_hooks=ln -sf /usr/bin/distrobox-host-exec /usr/local/bin/conmon;
init_hooks=ln -sf /usr/bin/distrobox-host-exec /usr/local/bin/crun;
init_hooks=ln -sf /usr/bin/distrobox-host-exec /usr/local/bin/docker;
init_hooks=ln -sf /usr/bin/distrobox-host-exec /usr/local/bin/docker-compose;
init_hooks=ln -sf /usr/bin/distrobox-host-exec /usr/local/bin/flatpak;
init_hooks=ln -sf /usr/bin/distrobox-host-exec /usr/local/bin/podman;
init_hooks=ln -sf /usr/bin/distrobox-host-exec /usr/local/bin/xdg-open;
#exported_apps="htop"
#exported_bins="/usr/bin/htop /usr/bin/git"
#exported_bins_path="~/.local/bin"
init_hooks="curl https://mise.run | sh"
#init_hooks=eval "$(mise activate bash)" # needs to be in .bashrc
#init_hooks="curl -fsSL https://install.determinate.systems/nix | sh -s -- install"
