# Source: https://distrobox.it/usage/distrobox-assemble/
[fedora_dev]
replace=true
image=registry.fedoraproject.org/fedora-toolbox:latest
additional_packages="acpi bash-completion findutils iproute iputils sensors inotify-tools unzip"
additional_packages="net-tools nmap openssl rsync man tig tmux tree vim nvim htop"
additional_packages="just"
additional_packages="git git-credential-libsecret"
#additional_packages="patterns-devel-base-devel_basis"
#additional_packages="ShellCheck ansible-lint clang clang-tools codespell ctags desktop-file-utils gcc jq"
additional_packages="kubernetes-client helm"
init_hooks=ln -sf /usr/bin/distrobox-host-exec /usr/local/bin/conmon;
init_hooks=ln -sf /usr/bin/distrobox-host-exec /usr/local/bin/crun;
init_hooks=ln -sf /usr/bin/distrobox-host-exec /usr/local/bin/docker;
init_hooks=ln -sf /usr/bin/distrobox-host-exec /usr/local/bin/docker-compose;
init_hooks=ln -sf /usr/bin/distrobox-host-exec /usr/local/bin/flatpak;
init_hooks=ln -sf /usr/bin/distrobox-host-exec /usr/local/bin/podman;
init_hooks=ln -sf /usr/bin/distrobox-host-exec /usr/local/bin/xdg-open;
exported_apps="htop"
exported_bins="/usr/bin/htop /usr/bin/git"
exported_bins_path="~/.local/bin"
start_now=true
init_hooks="curl https://mise.run | sh"
#init_hooks="dnf copr enable jdxcode/mise && dnf install mise"
#pre_init_hooks=curl -fsSL https://bun.sh/install | bash;
